export const database = {
  fish: [
    {
      name: "Nemo",
      species: "Clownfish",
      length: 3,
      location: "Great Barrier Reef",
      diet: "Omnivore",
      image:
        "https://lumiere-a.akamaihd.net/v1/images/07ff8e314e2798d32bfc8c39f82a9601677de34c.jpeg",
    },
    {
      name: "Dory",
      species: "Blue Tang",
      length: 5,
      location: "Great Barrier Reef",
      diet: "Omnivore",
      image:
        "https://www.washingtonpost.com/wp-apps/imrs.php?src=http://img.washingtonpost.com/rf/image_960w/2010-2019/Wires/Images/2016-04-27/AP/Film_Summer_Preview-0772a.jpg&w=1800&h=1800",
    },
    {
      name: "Jaws",
      species: "Great White",
      length: 12,
      location: "Cape Cod",
      diet: "People",
      image:
        "https://images.bauerhosting.com/legacy/empire-images/features/560ebc0750e6c513721c2fb0/2015-01-29-jaws1.jpeg?ar=16%3A9&fit=crop&crop=top&auto=format&w=480&q=80",
    },
    {
      name: "Common Goldfish",
      species: "Orange Fish",
      length: 1,
      location: "Fish Tank",
      diet: "Little kernels",
      image:
        "https://media.istockphoto.com/id/185331043/photo/goldfish-on-a-white-background.webp?a=1&b=1&s=612x612&w=0&k=20&c=f84ZSEq4RroRDP5W3iGnoPukT70LfydpvfKPDqaH7LU=",
    },
    {
      name: "Carp",
      species: "Lil Fatty",
      length: 3,
      location: "Pond",
      diet: "Other Fish?",
      image:
        "https://rivers.dwer.wa.gov.au/wp-content/uploads/2018/01/Carp_feature-image.jpg",
    },
    {
      name: "Piranha",
      species: "Sharp Boi",
      length: 2,
      location: "Rivers",
      diet: "Everything",
      image:
        "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQwJK6rxsS41pwauuJtTuo-qy72rC9DIBesiiGzMf9YovAYr9RehQTsptqpbWLttjsQiMAzLv7MDfEm9CSAKWesIg",
    },
    {
      name: "Dolphin",
      species: "Fren",
      length: 7,
      location: "Ocean",
      diet: "Stuff",
      image:
        "https://www.dolphinproject.com/wp-content/uploads/2020/07/Dolphin-Facts-1.jpg",
    },
    {
      name: "Goldie",
      species: "Goldfish",
      length: 3,
      location: "Freshwater Ponds",
      diet: "Herbivore",
      image: "https://example.com/images/goldie.jpg",
    },
    {
      name: "Bubbles",
      species: "Angelfish",
      length: 15,
      location: "Amazon Basin",
      diet: "Omnivore",
      image: "https://example.com/images/bubbles.jpg",
    },
    {
      name: "Stripe",
      species: "Zebra Pleco",
      length: 6,
      location: "Xingu River",
      diet: "Omnivore",
      image: "https://example.com/images/stripe.jpg",
    },
    {
      name: "Finn",
      species: "Betta",
      length: 4,
      location: "Rice Paddies",
      diet: "Carnivore",
      image: "https://example.com/images/finn.jpg",
    },
    {
      name: "Shadow",
      species: "Black Ghost Knifefish",
      length: 18,
      location: "Amazon Basin",
      diet: "Carnivore",
      image: "https://example.com/images/shadow.jpg",
    },
    {
      name: "Spike",
      species: "Pufferfish",
      length: 12,
      location: "Coral Reefs",
      diet: "Omnivore",
      image: "https://example.com/images/spike.jpg",
    },
    {
      name: "Spot",
      species: "Spotted Eagle Ray",
      length: 24,
      location: "Coastal Waters",
      diet: "Carnivore",
      image: "https://example.com/images/spot.jpg",
    },
    {
      name: "Rex",
      species: "Shark",
      length: 30,
      location: "Open Oceans",
      diet: "Carnivore",
      image: "https://example.com/images/rex.jpg",
    },
    {
      name: "Bella",
      species: "Swordfish",
      length: 45,
      location: "Deep Oceans",
      diet: "Carnivore",
      image: "https://example.com/images/bella.jpg",
    },
    {
      name: "Coral",
      species: "Wrasse",
      length: 5,
      location: "Tropical Reefs",
      diet: "Omnivore",
      image: "https://example.com/images/coral.jpg",
    },
    {
      name: "Splash",
      species: "Mahi-Mahi",
      length: 21,
      location: "Tropical Oceans",
      diet: "Carnivore",
      image: "https://example.com/images/splash.jpg",
    },
    {
      name: "Pebbles",
      species: "Guppy",
      length: 3,
      location: "Freshwater Streams",
      diet: "Omnivore",
      image: "https://example.com/images/pebbles.jpg",
    },
    {
      name: "Echo",
      species: "Rainbow Trout",
      length: 9,
      location: "Mountain Streams",
      diet: "Carnivore",
      image: "https://example.com/images/echo.jpg",
    },
    {
      name: "Glider",
      species: "Flying Fish",
      length: 12,
      location: "Open Waters",
      diet: "Omnivore",
      image: "https://example.com/images/glider.jpg",
    },
    {
      name: "Skye",
      species: "Moonfish",
      length: 27,
      location: "Deep Oceans",
      diet: "Carnivore",
      image: "https://example.com/images/skye.jpg",
    },
  ],
  tips: [
    {
      topic: "Water Temperature",
      text: "Maintain a consistent water temperature between 75-80°F (24-27°C) for most tropical fish.",
    },
    {
      topic: "Water Color",
      text: "Water should be clear and not murky.",
    },
    {
      topic: "Tank Lighting",
      text: "Should adjust based on time of day.",
    },
  ],
  location: [
    {
      name: "Great Barrier Reef",
      country: "Australia",
      description:
        "The Great Barrier Reef is the world's largest coral reef system, supporting a diverse array of marine life.",
    },
    {
      name: "Toilet Bowl",
      country: "Bathroom",
      description: "It's the toilet bowl...",
    },
    {
      name: "Fish Tank",
      country: "Living Room",
      description: "Hanging out in the living room!",
    },
  ],
};
